repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c "cd issue-bot && npm run lint"
        language: system
        files: issue-bot/.*\.ts$
        pass_filenames: false

      - id: prettier
        name: prettier
        entry: bash -c "cd issue-bot && npm run format:check"
        language: system
        files: issue-bot/.*\.ts$
        pass_filenames: false
