name: Test Code Review Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Run test script
      run: |
        cd code-review
        chmod +x test.sh
        ./test.sh
      env:
        OPENROUTER_KEY: ${{ secrets.OPENROUTER_KEY }}
